<?php

namespace ContainerYOR1S3s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromptControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PromptController' shared autowired service.
     *
     * @return \App\Controller\PromptController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PromptController.php';

        $container->services['App\\Controller\\PromptController'] = $instance = new \App\Controller\PromptController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PromptController', $container));

        return $instance;
    }
}
