<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWGwnOCE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWGwnOCE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWGwnOCE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWGwnOCE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWGwnOCE\App_KernelDevDebugContainer([
    'container.build_hash' => 'WGwnOCE',
    'container.build_id' => 'fce026db',
    'container.build_time' => 1698574072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWGwnOCE');
